// <auto-generated />
using System;
using Cart.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cart.Api.Data.Migrations
{
    [DbContext(typeof(CartDbContext))]
    partial class CartDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Cart.Api.Data.Entities.Aisle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Aisles");
                });

            modelBuilder.Entity("Cart.Api.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Cart.Api.Data.Entities.CategoryAisleMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AisleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AisleId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StoreId", "CategoryId", "AisleId")
                        .IsUnique();

                    b.ToTable("CategoryAisleMappings");
                });

            modelBuilder.Entity("Cart.Api.Data.Entities.Grocery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Groceries");
                });

            modelBuilder.Entity("Cart.Api.Data.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroceryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroceryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Cart.Api.Data.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Cart.Api.Data.Entities.Aisle", b =>
                {
                    b.HasOne("Cart.Api.Data.Entities.Store", "Store")
                        .WithMany("Aisles")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Cart.Api.Data.Entities.CategoryAisleMapping", b =>
                {
                    b.HasOne("Cart.Api.Data.Entities.Aisle", "Aisle")
                        .WithMany("CategoryAisleMappings")
                        .HasForeignKey("AisleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cart.Api.Data.Entities.Category", "Category")
                        .WithMany("CategoryAisleMappings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cart.Api.Data.Entities.Store", "Store")
                        .WithMany("CategoryAisleMappings")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aisle");

                    b.Navigation("Category");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Cart.Api.Data.Entities.Grocery", b =>
                {
                    b.HasOne("Cart.Api.Data.Entities.Category", "Category")
                        .WithMany("Groceries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Cart.Api.Data.Entities.Item", b =>
                {
                    b.HasOne("Cart.Api.Data.Entities.Grocery", "Grocery")
                        .WithMany("Items")
                        .HasForeignKey("GroceryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grocery");
                });

            modelBuilder.Entity("Cart.Api.Data.Entities.Aisle", b =>
                {
                    b.Navigation("CategoryAisleMappings");
                });

            modelBuilder.Entity("Cart.Api.Data.Entities.Category", b =>
                {
                    b.Navigation("CategoryAisleMappings");

                    b.Navigation("Groceries");
                });

            modelBuilder.Entity("Cart.Api.Data.Entities.Grocery", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Cart.Api.Data.Entities.Store", b =>
                {
                    b.Navigation("Aisles");

                    b.Navigation("CategoryAisleMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
